### ISSUE TITLE
Looks like missing some depedencies

### ISSUE THREAD

**Issue by fewensa** [darwinia-network/token-supply#2]
```
[GIN-debug] GET    /supply/ring              --> github.com/darwinia-network/token/middleware.PageCache.func1 (4 handlers)
[GIN-debug] GET    /supply/kton              --> github.com/darwinia-network/token/middleware.PageCache.func1 (4 handlers)
[GIN-debug] GET    /api/status               --> github.com/darwinia-network/token/server/routers/http.Run.func1 (4 handlers)
[GIN-debug] GET    /api/supply               --> github.com/darwinia-network/token/middleware.PageCache.func1 (4 handlers)
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x9728ae]

goroutine 36 [running]:
math/big.(*Int).Set(...)
        /opt/hostedtoolcache/go/1.18.3/x64/src/math/big/int.go:75
github.com/shopspring/decimal.NewFromBigInt(...)
        /home/runner/go/pkg/mod/github.com/shopspring/decimal@v1.3.1/decimal.go:123
github.com/darwinia-network/token/services/token.(*Currency).ethSupply(0xc0004180a0)
        /home/runner/work/token-supply/token-supply/services/token/supply.go:111 +0xce
github.com/darwinia-network/token/services/token.(*Currency).supply.func1()
        /home/runner/work/token-supply/token-supply/services/token/supply.go:70 +0x33
created by github.com/darwinia-network/token/services/token.(*Currency).supply
        /home/runner/work/token-supply/token-supply/services/token/supply.go:69 +0xea
```

When installed curl it's fixed

https://github.com/darwinia-network/token-supply/pull/1/commits/801c7259f6522aa6ef6bc39d457276951369f3f8

**Comment by cinlk** [comment]
It seems like   Eth  rpc calling failed that code parse data a nil value.
